Created models(User,Post,Tag,TagPost) and migrations
VsevolodEpihin/epihin_site_post_backend pull request #1
Opened 2024-05-31 12:09 UTC by VsevolodEpihin

2024-05-31 12:26 UTC, ekaterinagaltsova commented on .env.example
> +CLIENT="http://127.0.0.1:5502/"
+\n

2024-05-31 12:26 UTC, ekaterinagaltsova commented on .sequelizerc
> +const path = require('path');
передвинь к импортам

2024-05-31 12:26 UTC, ekaterinagaltsova commented on .sequelizerc
> +};
+\n

2024-05-31 12:26 UTC, ekaterinagaltsova commented on src/app.module.ts
> +import { SequelizeModule } from '@nestjs/sequelize';
непорядочный импорт

2024-05-31 12:26 UTC, ekaterinagaltsova commented on src/modules/posts/models/post.model.ts
> +import { User } from '../../users/user.model';
импорт(

2024-05-31 12:26 UTC, ekaterinagaltsova commented on src/modules/posts/models/post.model.ts
> +  @Column({
allowNull: false,
    unique: true,
    избыточны, ForeignKey это уже берет на себя

2024-05-31 12:26 UTC, ekaterinagaltsova commented on src/modules/posts/models/tagPost.model.ts
> +    unique: true,
не нать)

2024-06-03 06:47 UTC, s-skubedin requested changes

2024-06-03 06:47 UTC, s-skubedin commented on .sequelizerc
Зачем тут ConfigModule? Он только усложняет код, чтение и понимание.
Подключение ConfigModule глобально для всего проекта в файл, в который никто никогда не полезет - не безопасно, потом будут проблемы с рефактором и фиксами

2024-06-03 06:47 UTC, s-skubedin commented on db/migrations/20240531111853-create-users.js
> +      },
Используй timestamp option

2024-06-03 06:47 UTC, s-skubedin commented on db/migrations/20240531112013-create-posts.js
> +        },
То есть Null мы не разрешаем, а валидацию на отсутствие null убираем, так?

2024-06-03 06:47 UTC, s-skubedin commented on src/dto/create-post.dto.ts
Пустые файлы не должны находиться в репо

2024-06-03 07:33 UTC, VsevolodEpihin commented on .sequelizerc
Да, но ведь если я вынесу его отдельно в папку db, то файл конфига не всплывает,значения будут равны undefined

2024-06-03 11:35 UTC, s-skubedin requested changes

2024-06-03 11:35 UTC, s-skubedin commented on db/migrations/20240531111853-create-users.js
> +        timestamps: true,
Отсутствует стратегия именования автоматически генерируемых полей

2024-06-03 11:35 UTC, s-skubedin commented on .sequelizerc
Не совсем пойму вопроса, в config.js данные беруттся из process, а не из ConfigModule. В проекте ConfigModule должен подключаться в main или app

2024-06-04 11:25 UTC, s-skubedin approved these changes

2024-06-04 11:27 UTC, merged