described a JWT strategy, created 3 controllers for registration, authorization and receiving a user object by token
VsevolodEpihin/epihin_site_post_backend pull request #3
Opened 2024-06-19 07:50 UTC by VsevolodEpihin

described a JWT strategy for obtaining a token, created 3 controllers for registration, authorization and receiving a user object by token, created validation using DTO, hashed the user password using the bcrypt library

2024-06-19 11:11 UTC, ekaterinagaltsova commented on .env.example
> +SALT_ROUNDS=10
+/n

2024-06-19 11:11 UTC, ekaterinagaltsova commented on .env.example
> +SALT_ROUNDS=10
вот бы все в одинарных кавычках в енв

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/app.module.ts
> +    AuthModule,
есть ниже - зачем импортить дважды?

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/main.ts
> +  const config_service = app.get(ConfigService)
camelCase

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/main.ts
> +  const config_service = app.get(ConfigService)
cors?

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.controller.ts
> +import { Body, Controller, Get, Post, Headers } from "@nestjs/common";
single!!!

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.controller.ts
> +  constructor(private readonly authService: AuthService) {}
+/n

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.controller.ts
> +  @Post('login')
@Guard?

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.controller.ts
> +    return this.authService.loginUser(dto);
гвард вернет юзера - поймай его в контроллере и отправь в сервис для генерации токена

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.controller.ts
> +  @Get('whoAmI')
гвард с jwt стратегией?

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.controller.ts
> +  @Get('whoAmI')
who-am-i

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.controller.ts
> +  whoAmI(@Headers('Authorization') token: string) {
c Headers работае гвард - вернет юзера - верни его клиенту

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.module.ts
> +  providers: [AuthService, JwtStrategy],
+ localStrategy

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.module.ts
> +    CustomJwtModule,
CustomJwtModule глобален

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    const existUser = await this.userService.findUserByEmail(dto.email);
вызываешь функцию findUserByEmail до инициализации

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    if (existUser) throw new BadRequestException(AuthError.USER_EXIST);
явные проверки

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    const token = this.jwtService.sign(payload);
токен генерим по айди
this.jwtService.signAsync({ id });

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    const token = this.jwtService.sign(payload);
чтобы получить айди  - нужно создать запись о юзере в бд

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +  async loginUser(dto: UserLoginDto) {
на вход поступит юзер)

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +  async getUserFromToken(token: string) {
недооценил гварды)

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/dto/user-login.dto.ts
> +import { IsNotEmpty, IsString } from "class-validator";
single

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/auth/dto/user-login.dto.ts
> +  email: string;
нет защиты от пробелов

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/jwt/jwt.module.ts
> +import { JwtModule } from "@nestjs/jwt";
single

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/jwt/jwt.module.ts
> +    UserModule,
yt yfnm

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/jwt/jwt.strategy.ts
> +    if (!user) throw new BadRequestException(AuthError.WRONG_DATA);
not auth

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/users/dto/create-user.dto.ts
> +  @IsString()
пробелы(

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/jwt/jwt.strategy.ts
> +      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
так вот же работа по декодированию токена)

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/users/user.service.ts
> +  async removePassword(user: User) {
в функции не только удаляешь - но и получаешь
getUserWithoutPassword

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/users/user.service.ts
> +  async removePassword(user: User) {
на вход уже приходит юзер - зачем снова его искать

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/users/user.service.ts
> +      attributes: ["id","email","login","imageUrl"],
single quote

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/users/user.service.ts
> +  async hasPassword(password: string) {
hash?

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/users/user.service.ts
> +  async createUser(dto: CreateUserDto, token: string) {
было такое в auth

2024-06-19 11:11 UTC, ekaterinagaltsova commented on src/modules/users/users.controller.ts
> +  @Post('create-user')
move to auth

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/common/constants/errors.ts
> +export const AuthError = {
зачем с большой буквы?

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/main.ts
> +  app.enableCors({ origin: true });
настрой на свой фронт

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    return user.dataValues;
return user

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +  async removePassword(user: User) {
async избыточен

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/auth/auth.controller.ts
> +  @UseGuards(AuthGuard('local'))
тут иное

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    const userWithoutPassword = await this.removePassword(user.dataValues);
.removePassword(user);

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    if(existUser === null) throw new BadRequestException(AuthError.USER_NOT_EXIST);
+s

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    const validatePassword = await bcrypt.compare(password,existUser.password);
+s

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    if(validatePassword === false) throw new BadRequestException(AuthError.WRONG_DATA);
+s

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    if(validatePassword === false) throw new BadRequestException(AuthError.WRONG_DATA);
не сравниваем буль с булем!!!

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/auth/auth.service.ts
> +    if (existUser !== null && validatePassword) {
эти проверки уже были - сюда дойдет только нужный юзер

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/jwt/jwt.strategy.ts
> +      configService: ConfigService
+private readonly

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/jwt/jwt.strategy.ts
> +      throw new BadRequestException(AuthError.INVALID_TOKEN);
403

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/users/dto/create-user.dto.ts
> +  @Transform(createTransformParams)
пароль не тримим

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/modules/users/dto/user-login.dto.ts
> +  @Transform(createTransformParams)
top

2024-06-21 07:32 UTC, ekaterinagaltsova commented on src/type/index.ts
> +export interface JwtToken{
+s

2024-06-21 09:44 UTC, s-skubedin requested changes

2024-06-21 09:44 UTC, s-skubedin commented on src/modules/auth/auth.service.ts
> +  removePassword(user: User) {
Название не соответствует функционалу, происходит не удаление пароля, а создание user объекта.
Для удаления стоит использовать rest/spread оператор, деструктуризацию или delete оператор

2024-06-21 09:44 UTC, s-skubedin commented on src/modules/auth/auth.service.ts
> +  }
async/await избыточен, нет необходимости в создании дополнительной микрозадачи. Достаточно вернуть промис

2024-06-21 09:44 UTC, s-skubedin commented on src/modules/auth/auth.service.ts
> +    const existUser = await this.userRepository.findOne({ where: { email: dto.email } });
отсутствует attributes

2024-06-21 09:44 UTC, s-skubedin commented on src/modules/auth/auth.service.ts
> +      token: await this.generateToken(user.id),
Не стоит писать сложные конструкции в строчку, это усложняет чтение и понимание. Стоит вынести результат вызова функции в переменную

2024-06-24 05:42 UTC, s-skubedin commented on src/modules/auth/auth.service.ts
> +    const userWithoutPassword = delete existUser.dataValues.password;;
Если я не ошибаюсь, оператор delete возвращает boolean, а не объект
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete

2024-06-24 05:42 UTC, s-skubedin commented on src/modules/auth/auth.service.ts
> +    return userWithoutPassword;
Соблюдай пустые строки перед if и return

2024-06-24 05:42 UTC, s-skubedin commented on src/modules/auth/auth.service.ts
> +      attributes: attributes
Выносить attributes не нужно, это только усложняет код.
Если нужно только проверка на существование, то в `attributes` указывай пустой массив или только `id`

2024-06-24 06:50 UTC, s-skubedin approved these changes

2024-06-24 06:51 UTC, merged